additional_nas_paths:
- //192.168.0.181/Jellyfin6/Manga
chapter_delay_seconds: 2
check_interval_hours: 6
discord_webhook_url: ''
image_quality: data
komga_library_id: ''
komga_password: ''
komga_url: ''
komga_username: ''
language: en
manga:
- id: 8a9d2ae3-e896-4308-8c65-21e5e037cbef
  name: The Forbidden Lust of a Frigid Girl
- id: d36bea9f-853f-4908-9957-5514b1903e36
  name: Marika-chan no Koukando wa Bukkowarete iru
- id: 2fec6641-beb1-4ae9-a32f-204dd06688ac
  name: The Angel Next Door Spoils Me Rotten
- id: 8ef11280-30bc-434b-bf61-c61e092905ac
  name: I Made Friends with the Second Prettiest Girl in My Class
- id: f40eeb3a-c3a8-404d-a067-ca1831e60088
  name: Kamiina Botan Fully Blossoms When Drunk
- id: 26e4421f-cef8-4775-8bf6-423061d9b43e
  name: 'Classroom of the Elite: 2nd Year Arc - 2nd Stage'
- id: 22c844da-1122-4ab3-b726-e7d4b7114254
  name: Classroom of the Elite - 2nd Year Arc
- id: 6f81b440-3ece-4d24-ac12-1d460a1a3ca3
  name: Two-Person Town-Walking
- id: 8513b78c-cd7e-4efa-90d4-cab852430fd6
  name: I was Supposed to Never Fall in Love With You.
- id: 6f2b317e-17ff-491a-8f61-e6e591ae2df2
  name: Akanabe-sensei Doesn't Know About Embarrassment
- id: 4fd144b8-fc47-4cf4-afc7-9191d88dcc4a
  name: I, a Tired Office Worker, Start Living Together with a Beautiful Highschool
    Girl whom I Met Again After 7 Years
- id: 94f5cf68-7f42-4ad2-842f-15d5e787c9bb
  name: Youth Explosion!
- id: 85b3504c-62e8-49e7-9a81-fb64a3f51def
  name: Journey Home After School
- id: 5b6dc8cb-da4b-486d-88db-32f9c60d2dbc
  name: After Retiring, I Live My Life as a Stud in Another World
- id: f5c25341-d6ff-4585-8548-3a48fc7654d9
  name: Akira Failing in Love
- id: 984df7d5-ae4c-43c6-aa65-737b9f37e5ef
  name: My Bias Gets on the Last Train
- id: ee96e2b7-9af2-4864-9656-649f4d3b6fec
  name: Gals Can't Be Kind to Otaku
- id: 1464700f-62f5-4ae9-8e90-c2c99ffbf23f
  name: So This Is What Friends Do.
- id: 79ca6344-5468-4fa8-8eb7-859728b27156
  name: I Don't Know Which is Love
- id: 3bcc56f0-1b71-4542-b7b1-74db4fab2d72
  name: I Think I Turned My Childhood Friend Into a Girl
- id: 7991e715-40ae-4c3e-b0e0-aa8bee90ece7
  name: Me and the Prez, Drinking Under the Stars
- id: cfc35298-08f5-413a-976a-b0e0461e0ffa
  name: At Home with a Girl in Her Cute Pajamas
- id: bb5f1b24-58a6-49e4-847b-a322c2addbd5
  name: You're the Only One I Can See
- id: 91a2e0c9-cd81-4bf7-b5f7-bb37434bf6b3
  name: After School, We Wander in Space
- id: e2249870-322e-461f-9704-249d49d8fa89
  name: 'The Gal Sitting Behind Me Likes Me.: Maybe I''m Screwed Already.'
- id: 3bd65a09-dec5-4c0a-a34f-b07a9cc53aae
  name: I Made a Contract With Myself
- id: 50f4173e-744d-4f17-a74e-4e2ea177282d
  name: Love, Clairvoyance, and Adolescents
- id: c3295871-b930-4ee3-ac0f-ff7102ecec4e
  name: Sasha-chan and Her Classmate Otaku-kun
- id: 8bfde150-22b9-4361-9845-f2bb6957610b
  name: My Useless "Cuddle" Skill Awakened, and Now I’m Building the Ultimate Harem!
- id: 39e52698-160c-4f1a-b368-8fa4ac461c03
  name: My Girlfriend's Friend
- id: 9cd31469-d050-4523-b1eb-e019cd7f65d0
  name: After I Rescued a Cold-Hearted, Black-Haired, Beautiful Girl, She Started
    Acting Sweet Only When We Were Alone
- id: 85127c1f-1131-4fb2-9e36-8b45168a99e5
  name: Don't Touch, Kotesashi-kun
- id: a9ce0a44-ae4b-40b9-be3d-76e978cbbdad
  name: Hochiya-san is a Handful
- id: 9d985413-87c5-4990-9007-d5f4139535f5
  name: The School's Madonna, Watanabe-san, for Some Reason Asks My Schedule Every
    Week
- id: c4ca02fb-8378-433b-8049-fbbea5d25cba
  name: Haimiya-Senpai is Scary But Cute
- id: 74ad3ad0-41e2-4919-a3dd-e5061c3444da
  name: Why Don't You Make the Twins Your "Girlfriend" Together?
- id: 6370bf37-e997-4a5b-8651-3c5bb60c9c3a
  name: Mia is back
- id: 93f59355-6c69-416f-a5fb-84927eb31d42
  name: 'The Only Thing I''d Do in a No-Boys-Allowed Game World: Reincarnated as a
    Yuri Ship-Sinker'
- id: df361a38-eef6-4674-bec6-86d08aa1d1aa
  name: Tsumiki Ogami's Not-So-Ordinary Life
- id: 61830b36-1712-4b7b-9421-f671e9ced6d3
  name: Learning to Love My Cat-like Classmate
- id: c855ec45-b8d9-4aea-9a0d-b2ae544c11dc
  name: Tokimori-san Is Completely Defenseless!!
- id: 5e3a710f-0b0d-482b-9e84-d9c91960c625
  name: Anjo the Mischievous Gal
- id: f678b24d-f1fd-4717-8824-4138845390eb
  name: When I Repaired a Gal's Bicycle, She Became Attached to Me
- id: 77bee52c-d2d6-44ad-a33a-1734c1fe696a
  name: The Eminence in Shadow
- id: 28c77530-dfa1-4b05-8ec3-998960ba24d4
  name: 'Trapped in a Dating Sim: The World of Otome Games Is Tough for Mobs'
- id: a77742b1-befd-49a4-bff5-1ad4e6b0ef7b
  name: Chainsaw Man
- id: 3df1a9a3-a1be-47a3-9e90-9b3e55b1d0ac
  name: The Dangers in My Heart
- id: b4c93297-b32f-4f90-b619-55456a38b0aa
  name: More Than a Married Couple, But Not Lovers.
- id: 0b171f64-89a5-4c37-b5f9-75cca57e8787
  name: 'Failure Frame: I Became the Strongest and Annihilated Everything With Low-Level
    Spells'
- id: 39b4e02a-f2f2-4ff0-bf2c-f87cf54ab178
  name: 'Chronicles of an Aristocrat Reborn in Another World: The Apostle of the Gods
    Who Know No Self-Restraint'
- id: 1fc3d326-c037-43fa-8953-ed52a56caa18
  name: She's Likely Aiming for My Older Brother
- id: e0589f47-72f9-4e9a-ac31-5b88bcad6220
  name: The Wrong Way to Use Healing Magic
- id: 8352a9ca-22e0-4a1c-bf1f-89f23d95262a
  name: Campfire Cooking in Another World with My Absurd Skill
- id: 6bf844c8-2ce4-401a-a761-3151042efe30
  name: Alya Sometimes Hides Her Feelings in Russian
- id: 6b06fe1e-ff99-4c8d-be0b-5ad2a4df7603
  name: My Quiet Blacksmith Life in Another World
- id: fc6bbfc4-08f3-432d-914b-7fec244c001e
  name: Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside
- id: 30f3ac69-21b6-45ad-a110-d011b7aaadaa
  name: Fly Me to The Moon
- id: ed858324-c972-4d85-be4e-3287767eb7da
  name: 'My Life Turned Around: After Being Cheated on and Falsely Accused, I Ended
    up Being Adored by the Most Beautiful Girl in School'
- id: b198f9b8-7489-44cc-a062-1cb4b32d5507
  name: When Trying to Get Back at the Hometown Bullies, Another Battle Began.
- id: 6233aed2-2f42-4308-a2b9-7d37b836cc33
  name: Kusunoki's Flunking Her High School Glow-Up
- id: 1d330951-583e-423e-9cd7-abcd6f761f53
  name: My Older Sister's Friend
- id: 643561e6-5c27-4382-95d3-8e84894a3fb6
  name: My Love Story with Yamada-kun at Lv999
- id: d0c60a11-0106-45cf-abfc-d131cb49868f
  name: Beast Tamer
- id: 0301208d-258a-444a-8ef7-66e433d801b1
  name: I’m Gonna Live with You Not Because My Parents Left Me Their Debt But Because
    I Like You
- id: 77c8cc57-95c1-4f9b-8843-493eb2697566
  name: A Gatherer's Adventure in Isekai
- id: acdbf57f-bf54-41b4-8d92-b3f3d14c852e
  name: I Want to End This Love Game
- id: d553645b-03a3-4fc8-9a9c-57f91cbbab89
  name: Are You a Landmine, Chihara-san?
- id: 748d2aab-cea8-4ffb-89b3-e716872cb027
  name: 'A Slow Life After Being Expelled, Which I Never Wanted?: I was Supposed to
    Have Retired, but Somehow I Ended Up Becoming a Beautiful Girl''s Mentor, and
    for Some Reason, She Has Taken a Liking to Me.'
- id: 45b8d08e-b3ca-4aa7-bb14-120a1ed3c72f
  name: Wakaba Won't Give Up!
- id: 790f5f8d-0f9a-4f4b-92b3-9ac15f892b34
  name: 'Backstabbed in a Backwater Dungeon: My Party Tried to Kill Me, But Thanks
    to an Infinite Gacha I Got LVL 9999 Friends and am Out for Revenge'
- id: db692d58-4b13-4174-ae8c-30c515c0689c
  name: Hunter x Hunter
- id: 9afe47ee-5c8b-4572-b7c0-efa4f83da432
  name: 'Easygoing Territory Defense by the Optimistic Lord: Production Magic Turns
    a Nameless Village into the Strongest Fortified City'
- id: 270f205c-e9a6-4b24-b940-59d5c07829d1
  name: Otaku x Gal
- id: d0ddd740-4b91-4c66-bfd0-b36a77f8e730
  name: Brainrot Girlfriend
- id: 7fb957e4-a94b-496d-be91-b7d75fad7b21
  name: You can't Be in a Rom-Com with Your Childhood Friends!
- id: 099992b1-ce62-4a28-8133-d39c004ab470
  name: Turning the Tables on the Seatmate Killer!
- id: 4eb4943f-6f44-48a8-b40d-3e9a43dad0a1
  name: When the Introverted Me Got Surrounded by S-Tier Beauties After a Seat Change,
    a Secret Relationship Began
- id: ddcebfa2-05a0-4fcd-9cd4-60d779c38f2c
  name: Skilled Teaser (Former) Takagi-san
- id: 96b87943-6458-4045-a029-d3185d5cea57
  name: Onizuka-chan and Sawarida-kun
- id: 6378f4b1-f9a0-4233-b89a-95021535d100
  name: Mitsuishi-san Is Being Weird This Year
- id: 86d25eac-eb2f-4ec0-a341-f1a5cbbe80b8
  name: Let Me Be Single in Peace!
- id: a9c157f6-a720-4adc-87a4-79a3601aa4e8
  name: I Time-leaped 10 Years Ago and Saved My Childhood Friend, a Young Lady, and
    She became My Fiancée
- id: c9c13bf0-abd8-46a8-9b82-18c248b1db89
  name: The Handsome Girl Who Stole My Girlfriend Seems to be After Me Now
- id: 9c67e88c-ebbc-4dcc-bb92-b326283434ea
  name: Himegasaki Sakurako Is a Hot Mess
- id: 492e9584-b84b-4c78-afa1-71a747ba4ebe
  name: Sweet Cohabitation Romcom With My Senior Girlfriend and Alcohol Starts At
    Twenty
- id: 13df5a6e-1cee-466c-9f06-09f38fb012b7
  name: Love Lesson
- id: 7e3d081f-30f2-475d-83bb-e247cffea3d6
  name: Isshiki-san Wants to Know About Love.
- id: acfd6902-b39c-4b7d-91a8-9825dda4ede8
  name: The Story of Feeding the Cutest Gyaru in Class
- id: ffa0d510-e605-4bbe-8017-4295837718aa
  name: After School, at a Family Restaurant at Night, With That Girl From My Class
- id: 1c8f0358-d663-4d60-8590-b5e82890a1e3
  name: 'You Were Experienced, I was Not: Our Dating Story'
- id: f75c2845-0241-4e69-87c7-b93575b532dd
  name: You Like Me, Don't You?
- id: 2b37189e-0bb2-4586-9757-b3fe6acd77b3
  name: The War of Greedy Witches
- id: 65ab0e41-9cf9-420c-b860-2457d8cf403e
  name: The Demon King’s Daughter Wants to Marry the Hero in a Political Marriage
max_chapters_per_run: 0
nas_path: //192.168.0.181/Jellyfin2/Manga
new_manga_nas_path: ''
page_delay_seconds: 0.5
scrapers: {}
third_party_sites:
- base_url: https://mangakatana.com/manga/living-together-with-the-queaen-from-my-high-school-days-who-was-arrogant-surprisingly-isnt-that-uncomfortable.27631
  chapter_url_template: '{base_url}/c{num}'
  enabled: true
  name: Living Together with the Queen
  nas_folder: Living Together with the Queen
- base_url: https://ww6.onepiece-manga-online.net/manga/one-piece
  chapter_url_template: '{base_url}-chapter-{num}'
  enabled: true
  name: One Piece
  nas_folder: One Piece
web_port: 8080
webtoon_series:
- enabled: true
  name: Fog Land
  nas_folder: Fog Land
  url: https://www.webtoons.com/en/action/fog-land/list?title_no=9299
- name: My S-Class Hunters
  url: https://www.webtoons.com/en/action/my-s-class-hunters/list?title_no=3963
  nas_folder: My S-Class Hunters
  enabled: true
